#!/usr/bin/env bash
# Build Calliope: compile the Rust simulation to WASM (if sources changed),
# then assemble the static site into dist/.
#
# E6.10 — every phase is timed (ms) and the wall-times land in
# game/reports/build.txt beside the wasm size budget check (E6.4), so a
# build-time or binary-size regression shows up in the next report.sh
# summary sweep like any other failed band.
set -euo pipefail
cd "$(dirname "$0")/.."

RUST_DIR=game/rust
OUT=game/web/js/wasm
REPORT=game/reports/build.txt

now_ms() { date +%s%3N; }
T_START=$(now_ms)

needs_build=0
if [ ! -f "$OUT/calliope_bg.wasm" ]; then
  needs_build=1
elif [ -n "$(find "$RUST_DIR/src" "$RUST_DIR/Cargo.toml" -newer "$OUT/calliope_bg.wasm" -print -quit 2>/dev/null)" ]; then
  needs_build=1
fi

GEN=game/web/js/gen/constants.js
if [ ! -f "$GEN" ]; then
  needs_build=1
fi

if [ "$needs_build" = 1 ]; then
  echo "== rebuilding WASM engine =="
  if command -v wasm-pack >/dev/null 2>&1 && command -v cargo >/dev/null 2>&1; then
    (cd "$RUST_DIR" && wasm-pack build --target web --release)
    mkdir -p "$(dirname "$GEN")"
    (cd "$RUST_DIR" && cargo run -q --release --bin genjs) > "$GEN"
    (cd "$RUST_DIR" && cargo run -q --release --bin genjs -- types) > "$(dirname "$GEN")/types.js"
  else
    nix shell nixpkgs#rustc nixpkgs#cargo nixpkgs#lld nixpkgs#binaryen nixpkgs#wasm-pack -c \
      bash -c "cd '$RUST_DIR' && wasm-pack build --target web --release"
    mkdir -p "$(dirname "$GEN")"
    nix shell nixpkgs#rustc nixpkgs#cargo -c \
      bash -c "cd '$RUST_DIR' && cargo run -q --release --bin genjs" > "$GEN"
    nix shell nixpkgs#rustc nixpkgs#cargo -c \
      bash -c "cd '$RUST_DIR' && cargo run -q --release --bin genjs -- types" > "$(dirname "$GEN")/types.js"
  fi
  mkdir -p "$OUT"
  cp "$RUST_DIR/pkg/calliope.js" "$RUST_DIR/pkg/calliope_bg.wasm" "$OUT/"
else
  echo "== WASM engine up to date =="
fi
T_WASM=$(now_ms)

# Stamp the glue+wasm pair so the browser can never cache mismatched halves.
V=$(cat "$OUT/calliope.js" "$OUT/calliope_bg.wasm" | sha1sum | cut -c1-12)
printf '// generated by scripts/build.sh — cache stamp for the wasm pair\nexport const WASM_V = "%s";\n' "$V" > "$OUT/version.js"

rm -rf dist
mkdir -p dist
cp -r game/web/. dist/
T_SITE=$(now_ms)

# Brotli-precompress the wire-heavy artifacts (E3.10). scripts/serve.py
# negotiates Content-Encoding when a sibling .br exists; hosts that do
# their own compression simply ignore the extra files.
compress() {
  find dist -type f \( -name '*.js' -o -name '*.css' -o -name '*.html' -o -name '*.wasm' -o -name '*.json' \) -exec "$@" -f -q 10 -k {} +
}
if command -v brotli >/dev/null 2>&1; then
  compress brotli
elif nix shell nixpkgs#brotli -c brotli --version >/dev/null 2>&1; then
  compress nix shell nixpkgs#brotli -c brotli
else
  echo "== brotli unavailable — dist/ ships uncompressed =="
fi
T_BR=$(now_ms)

# ---- build report: phase times + wasm size budget (E6.4/E6.10) ------------
WASM_B=$(wc -c < "$OUT/calliope_bg.wasm")
BR_B=0
[ -f dist/js/wasm/calliope_bg.wasm.br ] && BR_B=$(wc -c < dist/js/wasm/calliope_bg.wasm.br)
# band: sweet ≤ 3.0 MiB, hard ≤ 3.4 MiB (measured 2.86 MiB after E6.2/E6.3)
SWEET=$((3 * 1024 * 1024))
HARD=$((3565158))
if   [ "$WASM_B" -le "$SWEET" ]; then MARK="[PASS]"
elif [ "$WASM_B" -le "$HARD" ];  then MARK="[WARN]"
else                                  MARK="[FAIL]"
fi
mkdir -p "$(dirname "$REPORT")"
{
  echo "========================================================================"
  echo " CALLIOPE DIAGNOSTIC · BUILD                              static site"
  echo "========================================================================"
  printf ' phase times: wasm %s ms · site %s ms · brotli %s ms · total %s ms\n' \
    "$((T_WASM - T_START))" "$((T_SITE - T_WASM))" "$((T_BR - T_SITE))" "$((T_BR - T_START))"
  printf ' wasm binary: %s B (%s.%s MiB) · brotli wire %s B · stamp %s\n' \
    "$WASM_B" "$((WASM_B / 1048576))" "$((WASM_B % 1048576 * 100 / 1048576))" "$BR_B" "$V"
  echo
  echo "---- checks ----------------------------------------------------------"
  printf '%s wasm binary size %36s B   (sweet ≤3.0 MiB · hard ≤3.4 MiB (E6.4))\n' "$MARK" "$WASM_B"
} > "$REPORT"
cat "$REPORT"

echo "== dist/ ready =="
