#!/usr/bin/env bash
# Build Calliope: compile the Rust simulation to WASM (if sources changed),
# then assemble the static site into dist/.
set -euo pipefail
cd "$(dirname "$0")/.."

RUST_DIR=game/rust
OUT=game/web/js/wasm

needs_build=0
if [ ! -f "$OUT/calliope_bg.wasm" ]; then
  needs_build=1
elif [ -n "$(find "$RUST_DIR/src" "$RUST_DIR/Cargo.toml" -newer "$OUT/calliope_bg.wasm" -print -quit 2>/dev/null)" ]; then
  needs_build=1
fi

GEN=game/web/js/gen/constants.js
if [ ! -f "$GEN" ]; then
  needs_build=1
fi

if [ "$needs_build" = 1 ]; then
  echo "== rebuilding WASM engine =="
  if command -v wasm-pack >/dev/null 2>&1 && command -v cargo >/dev/null 2>&1; then
    (cd "$RUST_DIR" && wasm-pack build --target web --release)
    mkdir -p "$(dirname "$GEN")"
    (cd "$RUST_DIR" && cargo run -q --release --bin genjs) > "$GEN"
    (cd "$RUST_DIR" && cargo run -q --release --bin genjs -- types) > "$(dirname "$GEN")/types.js"
  else
    nix shell nixpkgs#rustc nixpkgs#cargo nixpkgs#lld nixpkgs#binaryen nixpkgs#wasm-pack -c \
      bash -c "cd '$RUST_DIR' && wasm-pack build --target web --release"
    mkdir -p "$(dirname "$GEN")"
    nix shell nixpkgs#rustc nixpkgs#cargo -c \
      bash -c "cd '$RUST_DIR' && cargo run -q --release --bin genjs" > "$GEN"
    nix shell nixpkgs#rustc nixpkgs#cargo -c \
      bash -c "cd '$RUST_DIR' && cargo run -q --release --bin genjs -- types" > "$(dirname "$GEN")/types.js"
  fi
  mkdir -p "$OUT"
  cp "$RUST_DIR/pkg/calliope.js" "$RUST_DIR/pkg/calliope_bg.wasm" "$OUT/"
else
  echo "== WASM engine up to date =="
fi

# Stamp the glue+wasm pair so the browser can never cache mismatched halves.
V=$(cat "$OUT/calliope.js" "$OUT/calliope_bg.wasm" | sha1sum | cut -c1-12)
printf '// generated by scripts/build.sh — cache stamp for the wasm pair\nexport const WASM_V = "%s";\n' "$V" > "$OUT/version.js"

rm -rf dist
mkdir -p dist
cp -r game/web/. dist/

# Brotli-precompress the wire-heavy artifacts (E3.10). scripts/serve.py
# negotiates Content-Encoding when a sibling .br exists; hosts that do
# their own compression simply ignore the extra files.
compress() {
  find dist -type f \( -name '*.js' -o -name '*.css' -o -name '*.html' -o -name '*.wasm' -o -name '*.json' \) -exec "$@" -f -q 10 -k {} +
}
if command -v brotli >/dev/null 2>&1; then
  compress brotli
elif nix shell nixpkgs#brotli -c brotli --version >/dev/null 2>&1; then
  compress nix shell nixpkgs#brotli -c brotli
else
  echo "== brotli unavailable — dist/ ships uncompressed =="
fi

echo "== dist/ ready =="
